version: "3.1"

networks: 
    telebot:
        driver: bridge

services: 
    db:
        container_name: telegram_bot
        image: sameersbn/postgresql:10-2
        environment: 
            PG_PASSWORD: $PGPASSWORD
        restart: always
        ports: 
            - 5432:5432
        networks: 
            - telebot
        volumes: 
            - ./postgres:/var/lib/postgresql
    
    tgbot:
        container_name: bot
        build:
            context: .
        command: python app.py
        restart: always
        networks: 
            - telebot
        env_file:
            - ".env"
        volumes: 
            - .:/src
        depends_on: 
            - db
